### ISSUE TITLE
A12 support?

### ISSUE THREAD

**Issue by phattrance** [giorgioiavicoli/PassBy#4]
Willl this tweak be updated for a12 devices?

**Comment by phattrance** [comment]
Screenshot https://i.imgur.com/8eZp2qZ

**Comment by Fidelity88** [comment]
Same here!

**Comment by mads0n69** [comment]
Need A12 love too! Thank you!

**Comment by systox** [comment]
Another voice to the a12 crowd. I hate having to unlock phone with code when phone is docked while driving.

**Comment by blueman007** [comment]
Same. Would love to have A12 support, currently "There was an error loading the preference bundle for Passby".

**Comment by FaZeIlLuMiNaTi** [comment]
This tweak is updated for A12, just not compiled. Simply cloning this repo and compiling with theos on macOS makes this tweak work on A12 devices. Here's a copy I compiled for a friend with an XS Max.
[com.giorgioiavicoli.passby_1.8.3_iphoneos-arm.deb.zip](https://github.com/giorgioiavicoli/PassBy/files/4134588/com.giorgioiavicoli.passby_1.8.3_iphoneos-arm.deb.zip)

**Comment by kmokhtar79** [comment]
> This tweak works on A12 devices, it’s just not compiled. Simply cloning this repo and compiling with theos on macOS makes this tweak work on A12 devices. Here's a copy I compiled for a friend with an XS Max.
> [com.giorgioiavicoli.passby_1.8.3_iphoneos-arm.deb.zip](https://github.com/giorgioiavicoli/PassBy/files/4134588/com.giorgioiavicoli.passby_1.8.3_iphoneos-arm.deb.zip)

Thank you for compiling it for A12 devices. I am currently using it on unc0ver 5 ios 13.5, however there is a animation delay to unlock the device (specially when LPM is enabled). Would you please look check if it's possible to fix the delay issue as well. Highly appreciate it.

**Comment by edgarfroes** [comment]
> This tweak works on A12 devices, it’s just not compiled. Simply cloning this repo and compiling with theos on macOS makes this tweak work on A12 devices. Here's a copy I compiled for a friend with an XS Max.
> [com.giorgioiavicoli.passby_1.8.3_iphoneos-arm.deb.zip](https://github.com/giorgioiavicoli/PassBy/files/4134588/com.giorgioiavicoli.passby_1.8.3_iphoneos-arm.deb.zip)

This link isn't working anymore.

**Comment by systox** [comment]
> > This tweak works on A12 devices, it’s just not compiled. Simply cloning this repo and compiling with theos on macOS makes this tweak work on A12 devices. Here's a copy I compiled for a friend with an XS Max.
> > [com.giorgioiavicoli.passby_1.8.3_iphoneos-arm.deb.zip](https://github.com/giorgioiavicoli/PassBy/files/4134588/com.giorgioiavicoli.passby_1.8.3_iphoneos-arm.deb.zip)
> 
> This link isn't working anymore.


Working when I just tested it. Might have been a transient issue.

**Comment by systox** [comment]
But.. heads up the tweak does not work reliably on iOS 13.5 Ip11pm. No Apple Watch support. Will randomly stop functioning.

**Comment by KihtrakRaknas** [comment]
wifi unlock crashes device for me
