### ISSUE TITLE
ios13？

### ISSUE THREAD

**Issue by trulynb** [giorgioiavicoli/PassBy#6]
please   嘤嘤嘤

**Comment by systox** [comment]
Works on 13.5 Ip11pm. Use the a12 deb in the other issues thread.

Not working: CarPlay and Apple Watch integration

**Comment by trulynb** [comment]
> Works on 13.5 Ip11pm. Use the a12 deb in the other issues thread.
> 
> Not working: CarPlay and Apple Watch integration

thanks man
